name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build com java 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'Iurydev/pom.xml' # optional
      - name: Build with Maven
        run: mvn -B package --file pom.xml